use empresa;
insert into funcionario values(1, 'Dono da Empresa', 'Rua X', 1, '11111-111', 'SP', 10000.00, null, null);
insert into departamento values(1, 'Financeiro', 1, '2010-08-20');
insert into departamento(nome, numero, numerofuncger, dataini) values('Recursos Humanos', 2, null, null);
insert into departamento(numero, nome) values(3, 'Auditoria');
insert into departamento(numero, nome) values(4, 'Compras');
insert into departamento(numero, nome) values(5, 'Compras');
delete from departamento where numero = 5;
insert into funcionario values(2, 'Dono da Empresa', 'Rua X', 1, '11111-111', 'SP', 20000, null, null);
delete from funcionario where salario > 10000 and salario <= 20000;
update funcionario set salario = salario * 1.05;
insert into funcionario values(2, 'Funcionario 2', 'Rua Y', 2, '11111-222', 'SP', 990.50, 1, 1);
update funcionario set salario = salario * 1.05 where salario < 1000;
update funcionario set salario = salario * 1.05, rua = 'Rua UUU' where salario < 1100;
select numero, nome from funcionario;
select numero, nome from funcionario where salario > 5000;
select numero, nome from funcionario where numero >= 2;
select numero, nome, estado from funcionario where numerodepto = 1;
select f.numero, f.nome, f.estado, d.numero, d.nome from funcionario f, departamento d where f.numerodepto = d.numero;
select f.numero, f.nome, f.estado, d.numero, d.nome from funcionario f, departamento d where f.numerodepto = d.numero and salario > 500;
select nome, salario from funcionario where salario between 500.25 and 1500.50;
select nome, salario from funcionario where nome = 'Funcionario 2';
select nome, salario from funcionario where nome like 'Funcionario%';
select nome, salario from funcionario where nome like '%2';
select nome, salario from funcionario where nome like '%ar%';
select * from funcionario where numerodepto is null;
select * from funcionario where numerodepto is not null;
select * from funcionario order by nome desc;
select * from funcionario order by salario;
select * from funcionario order by salario desc;
